privacy-ethereum/maci-platform

src/layouts/DefaultLayout.tsx

Remove lists page from default layout navigation

feat: remove lists page from navigation

---

package.json
pnpm-lock.yaml
src/pages/api/auth/[...nextauth].ts

feat: generate maci keypair

---

.env.example
package.json
pnpm-lock.yaml
src/components/ConnectButton.tsx
src/config.ts
src/env.js
src/hooks/useMaciSignup.ts
src/server/api/routers/voters.ts
src/server/auth.ts
src/utils/fetchAttestations.ts

feat: maci signup

---

package.json
pnpm-lock.yaml
src/components/ConnectButton.tsx
src/config.ts
src/features/ballot/components/BallotOverview.tsx
src/features/ballot/components/VotingEndsIn.tsx
src/features/lists/components/ListEditDistribution.tsx
src/features/projects/components/Projects.tsx
src/features/projects/components/ProjectsResults.tsx
src/hooks/useMaciPoll.ts
src/hooks/useMaciSignup.ts
src/hooks/useResults.ts
src/layouts/DefaultLayout.tsx
src/pages/api/auth/[...nextauth].ts
src/pages/ballot/index.tsx
src/pages/projects/[projectId]/index.tsx
src/pages/stats/index.tsx
src/providers/RainbowKitSiweNextAuthProvider.tsx
src/providers/index.tsx
src/server/api/routers/ballot.ts
src/utils/state.ts

Blocked by #20 
Closes #10
Closes #11

feat: use onchain poll data 

---

pnpm-lock.yaml
public/mockServiceWorker.js
src/components/ConnectButton.tsx
src/components/ui/Card.tsx
src/components/ui/Divider.tsx
src/components/ui/index.tsx
src/features/ballot/components/BallotConfirmation.tsx
src/features/ballot/components/BallotOverview.tsx
src/features/projects/components/AddToBallot.tsx
src/features/projects/components/Projects.tsx
src/hooks/useMaciSignup.ts
src/hooks/useResults.ts
src/providers/index.tsx
src/styles/globals.css
src/utils/fetchAttestations.ts
src/utils/state.ts
tsconfig.json

feat: improve signup flow

---

docs/01_setup.md
docs/04_voting.md
docs/05_lists.md
docs/06_results.md

docs: update docs with maci integration steps

---

.env.example
src/components/ConnectButton.tsx
src/features/ballot/components/AllocationInput.tsx
src/features/ballot/components/AllocationList.tsx
src/features/lists/components/ListCreateForm.tsx
src/pages/ballot/index.tsx
src/pages/stats/index.tsx
src/providers/index.tsx
src/utils/formatNumber.ts

fix: demo ui

---

.env.example
package.json
pnpm-lock.yaml
src/features/ballot/components/BallotOverview.tsx
src/hooks/useEthersSigner.ts
src/hooks/useMaciPoll.ts
src/providers/index.tsx

Add infura fallback provider for reading blockchain data if user doesn't have connected wallet

feat: add fallback provider to get blockchain data

---

src/pages/stats/index.tsx

Note: ethers handle retry logic, so just need to wait 4 seconds to get missing data. For demo it's enough to have free infura account.

fix: rate limit error handling

---

package.json
pnpm-lock.yaml
src/services/maci/service.ts

fix: update maci-cli version

---

.env.example
README.md
docs/01_setup.md

- Updated Readme
- Update sample.env
- Updated setup with a guide to run MACI

docs: updated readme and setup guide

---

src/services/maci/service.ts

Remove getting AccQueue from `MACI` contract and remove the registration for AccQueue to ContractStorage.

Chore: update maci service

---

src/pages/api/auth/[...nextauth].ts
src/providers/RainbowKitSiweNextAuthProvider.tsx

Ensure that the message to be signed with the user's wallet is the same for each domain they connect to.
fix #75

fix: make key generation deterministic

---

src/features/admin/components/InvalidAdmin.tsx
src/layouts/AdminLayout.tsx
src/layouts/DefaultLayout.tsx
src/pages/applications/index.tsx
src/pages/distribute/index.tsx
src/pages/voters/index.tsx

- Fixes AdminLayout
- Add AdminLayout to Applications, Voters, and Distribute pages.
- Added link to info page in any Layout.
Fixes #95

Fix: Permissions to admin pages

---

src/contexts/Maci.tsx
src/hooks/useEthersSigner.ts

The original useEthersSigner hook is outdated, sync this file upstream.

fix: update useEthersSigner

---

src/features/applications/types/index.ts

chore: accept URLs without http/https

---

docs/01_setup.md

Update docs to reflect poll finalization

docs: update setup with poll finalization

---

src/server/api/routers/results.ts

this is copy from this commit: https://github.com/gitcoinco/easy-retro-pgf/commit/c6d2996a9d02388cc03f8cdc5acc47309aa1b920
to hide voting result from the public.

chore: hide result votes

---

src/layouts/DefaultLayout.tsx

temporally removed distribution from admin navigation

---

src/features/ballot/components/BallotOverview.tsx

added border to create application

added border to create application button

---

package.json
pnpm-lock.yaml

chore: update to maci-cli 1.2.3

---

README.md
docs/01_setup.md

- added v1.2.3 on docs
- fixed broken links

Docs/update v1.2.3

---

src/components/ConnectButton.tsx
src/components/ui/Form.tsx
src/contexts/Ballot.tsx
src/contexts/Maci.tsx
src/contexts/types.ts
src/features/ballot/components/AllocationList.tsx
src/features/ballot/components/BallotOverview.tsx
src/features/lists/components/ListCreateForm.tsx
src/features/lists/components/ListEditDistribution.tsx
src/features/projects/components/AddToBallot.tsx
src/features/projects/hooks/useSelectProjects.ts
src/pages/ballot/confirmation.tsx
src/pages/ballot/index.tsx
src/providers/index.tsx

feat: create ballot context and fix several bugs

---

src/contexts/Ballot.tsx
src/contexts/Maci.tsx
src/contexts/types.ts
src/features/ballot/components/BallotOverview.tsx

remove unused ballot in maci context and set published to true on vote succeed

chore: set `published` to true after submitting vote

---

.env.example
docs/01_setup.md
package.json
pnpm-lock.yaml
src/config.ts
src/contexts/Maci.tsx
src/env.js
src/server/api/root.ts
src/server/api/routers/maci.ts
src/utils/fetchUser.ts

feat(subgraph): add subgraph integration

---

README.md
docs/01_setup.md

Remove redundant entries from docs

docs: cleanup docs

---

src/components/Header.tsx
src/components/ui/Button.tsx
src/components/ui/Dialog.tsx
src/components/ui/Input.tsx
src/components/ui/Notification.tsx
src/components/ui/Table.tsx
src/contexts/Ballot.tsx
src/contexts/Maci.tsx
src/contexts/types.ts
src/env.js
src/features/ballot/components/AllocationInput.tsx
src/features/ballot/components/AllocationList.tsx
src/features/ballot/components/BallotConfirmation.tsx
src/features/ballot/components/ProjectAvatarWithName.tsx
src/features/ballot/components/SubmitBallotButton.tsx
src/features/projects/components/ProjectItem.tsx
src/layouts/BaseLayout.tsx
src/layouts/DefaultLayout.tsx
src/pages/ballot/confirmation.tsx
src/pages/ballot/index.tsx
src/pages/projects/[projectId]/Project.tsx
src/pages/projects/index.tsx
src/providers/index.tsx
src/styles/globals.css

feat: modify ballot page styling

---

src/components/ConnectButton.tsx
src/components/EligibilityDialog.tsx
src/components/Header.tsx
src/components/JoinButton.tsx
src/components/SortByDropdown.tsx
src/components/ui/Button.tsx
src/components/ui/Dialog.tsx
src/components/ui/Link.tsx
src/components/ui/Tag.tsx
src/features/ballot/components/AllocationList.tsx
src/features/projects/components/ProjectContacts.tsx
src/features/projects/components/ProjectDescriptionSection.tsx
src/features/projects/components/ProjectItem.tsx
src/features/projects/components/VotingWidget.tsx
src/layouts/BaseLayout.tsx
src/pages/ballot/index.tsx
src/pages/signup/index.tsx

- update `Button` component variant
- update every `button` with `Button` component (customized button)
- update some `Link` from `next/link` to customized `Link` component
- update hover style of customized `Button` and `Link`
- update hover style of `ProjectItem`
- update background color

feat: update hover style base on figma design

---

.env.example
.eslintignore
.gitignore
.prettierignore
README.md
docs/01_setup.md
docs/06_maci_troubleshooting.md
public/mockServiceWorker.js
src/env.js
src/server/api/routers/results.ts
tsconfig.json

- Removed nextauth variables
- Changed default values on env.example
- Added video tutorial

fix(env-docs): removed auth variables and improved docs

---

.env.example
docs/01_setup.md
package.json
pnpm-lock.yaml
src/config.ts
src/contexts/Maci.tsx
src/contexts/types.ts
src/env.js
src/hooks/useDeployment.ts
src/pages/coordinator/index.tsx
src/services/maci/constants.ts
src/services/maci/service.ts
src/services/maci/types.ts

try to call coordinator service api to make sure everything works well.
**Blocker**
PR #170 
https://github.com/privacy-scaling-explorations/maci/pull/1584
**Problem**
Deployed coordinator service in the local side, but always got `400 Bad Request`.
For the nest side, the error message is 
```
[Nest] 71842  - 2024/06/19 上午2:33:03   ERROR [AppController] Error:
[Nest] 71842  - 2024/06/19 上午2:33:03   ERROR [AppController] Error: contract runner does not support calling (operation="call", code=UNSUPPORTED_OPERATION, version=6.13.0)
```
#139

feat: call coordinator service api

---

src/contexts/Maci.tsx

solve #183.
The problem is explained in the issue.

fix: recurring dependency in maci context

---

src/contexts/Maci.tsx
src/server/api/routers/maci.ts
src/utils/fetchPoll.ts

Fetch poll data from subgraph and as fallback from the contract. 
fix #154 
Code mostly by @crisgarner

feat: fetch poll data from subgraph

---

.github/workflows/e2e.yml

Use node v20 for coactions/setup-xvfb

chore: update coactions/setup-xvfb to use node v20

---

src/hooks/useMetadata.ts

fix: ensure uploaded files are valid

---

src/config.ts
src/features/applications/components/ImpactTags.tsx
src/providers/index.tsx
src/utils/semaphore.ts

Add a function to get RPC URLs dynamically based on the network we are connected to

chore: add function to get rpc-urls dynamically

---

src/components/Toaster.tsx

feat: modify toaster styling

---

src/components/EligibilityDialog.tsx
src/components/JoinButton.tsx

Change the if...else in the `EligibilityDialog`
close #219

fix: eligibility dialog display

---

src/components/BallotOverview.tsx
src/contexts/Ballot.tsx
src/features/ballot/types/index.ts
src/features/projects/components/Projects.tsx
src/layouts/DefaultLayout.tsx
src/pages/ballot/index.tsx

fix several ballot and voting bugs
close #171

fix: multiple ballot issues

---

packages/interface/.env.example
packages/interface/src/components/BallotOverview.tsx
packages/interface/src/components/RoundInfo.tsx
packages/interface/src/components/ui/Form.tsx
packages/interface/src/components/ui/Heading.tsx
packages/interface/src/config.ts
packages/interface/src/contexts/Maci.tsx
packages/interface/src/features/applications/components/ApplicationsToApprove.tsx
packages/interface/src/features/applications/components/ReviewApplicationDetails.tsx
packages/interface/src/features/ballot/components/BallotConfirmation.tsx
packages/interface/src/features/projects/components/ProjectDetails.tsx
packages/interface/src/features/projects/components/Projects.tsx
packages/interface/src/features/signup/components/FaqList.tsx
packages/interface/src/features/voters/components/VotersList.tsx
packages/interface/src/hooks/useEthersSigner.ts
packages/interface/src/layouts/BaseLayout.tsx
packages/interface/src/pages/applications/confirmation.tsx
packages/interface/src/pages/applications/new.tsx
packages/interface/src/pages/ballot/index.tsx
packages/interface/src/pages/info/index.tsx
packages/interface/src/pages/signup/index.tsx
packages/interface/src/pages/stats/index.tsx
packages/interface/src/pages/voters/index.tsx
packages/interface/src/styles/globals.css
packages/interface/src/utils/state.ts
packages/interface/src/utils/types.ts

This PR should be the last PR for the v1 and the feat/design-ui branch, which is running through all the operations after creating monorepo and to see if there's any improvements could be done.

chore: fixing small and minor issues

---

packages/interface/src/features/projects/components/ProjectItem.tsx

Just a small fix to avoid long warning on console
close #252

fix(interface): prevent component hierarchy warning

---

packages/contracts/.solcover.js
packages/contracts/contracts/interfaces/IOwnable.sol
packages/contracts/contracts/interfaces/IPoll.sol
packages/contracts/contracts/maci/MACI.sol
packages/contracts/contracts/maci/Poll.sol
packages/contracts/contracts/maci/PollFactory.sol
packages/contracts/contracts/mocks/Mocker.sol
packages/contracts/package.json
packages/contracts/scripts/compileSol.ts
packages/contracts/tests/Poll.test.ts
packages/contracts/tests/constants.ts
packages/contracts/tests/utils.ts
pnpm-lock.yaml

feat(contracts): add custom maci contracts

---

packages/interface/src/features/ballot/components/AllocationInput.tsx
packages/interface/src/features/projects/components/VotingWidget.tsx

fix: not allow input negative values for votes

---

packages/interface/src/components/EligibilityDialog.tsx

update the "X" with real number or string.
**Issues**
close #286

fix: update X with real number

---

packages/interface/src/contexts/Maci.tsx
packages/interface/src/contexts/types.ts
packages/interface/src/layouts/DefaultLayout.tsx

Do not show voters page when the Gatekeeper is not EAS

feat: do not show voters page when gatekeeper is not EAS

---

packages/interface/src/contexts/Maci.tsx

fix: ensure poll end date is in the future

---

packages/interface/src/components/BallotOverview.tsx
packages/interface/src/components/VotingUsage.tsx
packages/interface/src/contexts/Maci.tsx
packages/interface/src/features/applications/components/ReviewBar.tsx
packages/interface/src/features/ballot/components/BallotConfirmation.tsx
packages/interface/src/features/projects/components/Projects.tsx
packages/interface/src/pages/applications/confirmation.tsx
packages/interface/src/pages/applications/new.tsx
packages/interface/src/pages/ballot/index.tsx

Change several wordings
close #331

chore: update the wordings

---

packages/interface/src/components/BallotOverview.tsx
packages/interface/src/components/Info.tsx
packages/interface/src/components/VotingInfo.tsx
packages/interface/src/layouts/DefaultLayout.tsx
packages/interface/src/pages/signup/index.tsx

adjust the order and structure of `Info` widget
**Related Issue**
close #333

chore: update info and ballot overview display

---

docs/01_setup.md

- Updated video tutorials to new version.

docs(setup-docs): updated video tutorials

---

docs/01_setup.md

Added some updates to versions and added the improved rewording and explanations by @daniel0ar in https://github.com/privacy-scaling-explorations/maci-platform/pull/358 🙏

docs(updated-setup)

---

packages/interface/src/features/applications/components/ApplicationItem.tsx

According to the description of the PR: #370

fix: clear selected checkbox after approved

---

packages/contracts/contracts/mocks/Mocker.sol
packages/subgraph/config/network.json
packages/subgraph/package.json

- Added Zupass to the mock contract
- Changed order of the block for the network config (more clear with this grouping)
- Changed deploy command subgraph name

feat(Mock-contracts): added zupass contract to mocks

---

packages/interface/src/components/Footer.tsx
packages/interface/src/components/Header.tsx
packages/interface/src/features/applications/components/ApplicationForm.tsx
packages/interface/src/features/applications/components/ApplicationHeader.tsx
packages/interface/src/features/applications/components/ApplicationItem.tsx
packages/interface/src/features/applications/components/ApplicationSteps.tsx
packages/interface/src/features/applications/components/ApproveButton.tsx
packages/interface/src/features/applications/components/ReviewApplicationDetails.tsx
packages/interface/src/features/applications/components/SelectAllButton.tsx
packages/interface/src/features/ballot/components/AllocationFormWrapper.tsx
packages/interface/src/features/ballot/components/BallotConfirmation.tsx
packages/interface/src/features/home/components/FaqItem.tsx
packages/interface/src/features/home/components/FaqList.tsx
packages/interface/src/features/projects/components/ProjectContacts.tsx
packages/interface/src/features/projects/components/ProjectDetails.tsx
packages/interface/src/features/projects/components/ProjectItem.tsx
packages/interface/src/features/projects/components/VotingWidget.tsx
packages/interface/src/features/rounds/components/Projects.tsx
packages/interface/src/features/rounds/components/RoundsList.tsx
packages/interface/src/hooks/useScreenSize.ts
packages/interface/src/layouts/BaseLayout.tsx
packages/interface/src/pages/index.tsx
packages/interface/src/pages/rounds/[roundId]/applications/confirmation.tsx
packages/interface/src/pages/rounds/[roundId]/ballot/index.tsx

related to PR #399 
This is the rebase main branch version.

fix: mobile support for multi-round UI

---

packages/interface/src/features/rounds/components/Projects.tsx

fix: add create application button back to the round page

---

packages/interface/src/features/projects/components/VotingWidget.tsx

"when adding a vote from project page and removing it from ballot, I can’t add it again. Need to refresh."
Merge first the other 3 PRs (#407 #414 #415)

fix: edit ballot

---

packages/interface/src/components/ui/Notice.tsx
packages/interface/src/features/ballot/components/AllocationFormWrapper.tsx
packages/interface/src/features/ballot/components/AllocationInput.tsx
packages/interface/src/features/ballot/components/ProjectAvatarWithName.tsx
packages/interface/src/features/rounds/components/RoundItem.tsx
packages/interface/src/pages/rounds/[pollId]/ballot/index.tsx

fixes #319, #384, and some small bugs with dark mode.
Here is a preview of the implementation:
https://github.com/user-attachments/assets/2c1bf9d4-97c4-4cad-a738-96e1c904bf40

feat(ballot-page): added stepper and improvements

---

packages/interface/src/features/ballot/components/ProjectAvatarWithName.tsx

fix issue where ballot shows banner instead of profile

fix(project-avatar): fix issue where ballot shows banner instead 

---

.github/workflows/subgraph.yml
.prettierignore
packages/contracts/contracts/maci/Tally.sol
packages/contracts/tests/Tally.test.ts
packages/subgraph/.gitignore
packages/subgraph/package.json
packages/subgraph/schemas/schema.v1.graphql
packages/subgraph/scripts/cleanAbi.ts
packages/subgraph/src/registryManager.ts
packages/subgraph/src/tally.ts
packages/subgraph/src/utils/entity.ts
packages/subgraph/templates/subgraph.template.yaml
packages/subgraph/tests/common.ts
packages/subgraph/tests/poll/poll.test.ts
packages/subgraph/tests/registryManager/registryManager.test.ts
packages/subgraph/tests/registryManager/utils.ts
packages/subgraph/tests/tally/tally.test.ts
packages/subgraph/tests/tally/utils.ts
packages/subgraph/tsconfig.build.json
packages/subgraph/tsconfig.json
pnpm-lock.yaml
tsconfig.json

feat(subgraph): add tally event handlers

---

packages/contracts/contracts/interfaces/IPayoutStrategy.sol
packages/contracts/contracts/maci/Tally.sol
packages/contracts/deploy-config-example.json
packages/contracts/tasks/deploy/poll/01-poll.ts
packages/contracts/tests/Tally.test.ts

feat(contracts): add max cap for allocated amount

---

packages/contracts/deploy-config-example.json
packages/contracts/hardhat.config.ts
packages/contracts/package.json
packages/contracts/tasks/deploy/maci/05-pollFactory.ts
packages/contracts/tasks/deploy/maci/07-tallyFactory.ts
packages/contracts/tasks/deploy/maci/08-maci.ts
packages/contracts/tasks/deploy/maci/10-registryManager.ts
packages/contracts/tasks/deploy/poll/01-poll.ts
packages/contracts/tasks/helpers/constants/index.ts
packages/contracts/tasks/runner/initPoll.ts
packages/contracts/tasks/runner/merge.ts
packages/contracts/tasks/runner/prove.ts
packages/contracts/tasks/runner/submitOnChain.ts
packages/contracts/tests/utils.ts
pnpm-lock.yaml

Set contract names for deployment helper service and add updated prove/submitOnChain tasks
Closes #433

feat(contracts): set contract names for deployment helper service

---

packages/contracts/tasks/deploy/poll/01-poll.ts
packages/coordinator/scripts/downloadZKeys.ts
packages/subgraph/config/network.json
packages/subgraph/src/maci.ts
packages/subgraph/src/utils/entity.ts
packages/subgraph/tests/common.ts
packages/subgraph/tests/poll/poll.test.ts

Added missing tally entity creator
Related to #263

fix(subgraph): add create tally handler to parse tally events

---

packages/interface/src/contexts/Round.tsx
packages/interface/src/features/results/components/ResultItem.tsx
packages/interface/src/hooks/useEthersSigner.ts
packages/interface/src/pages/rounds/[pollId]/result/index.tsx
packages/interface/src/utils/accountAbstraction.ts

Show the amount to be distributed to projects

feat: show amount devcon round

---

.gitignore
packages/interface/package.json
packages/interface/src/components/Header.tsx
packages/interface/src/components/JoinButton.tsx
packages/interface/src/config.ts
packages/interface/src/contexts/Maci.tsx
packages/interface/src/contexts/types.ts
packages/interface/src/features/home/components/FaqList.tsx
packages/interface/src/pages/api/poap.ts
packages/interface/src/pages/index.tsx
packages/interface/src/utils/db.ts
pnpm-lock.yaml

POAP claim button

---

packages/interface/src/components/ConnectButton.tsx

Ref #282 
Displays the ENS name on the connect button if it is available

feat: display ENS if available

---

packages/interface/src/server/api/routers/results.ts

change `fetchProjects` to `fetchApprovedProjects`
close #508

fix: only display tally results of approved projects

---

docs/01_setup.md
packages/coordinator/package.json
packages/coordinator/scripts/generateMaciKeyPair.ts

docs(updated-docs): updated docs to support multiround

---

packages/interface/src/pages/index.tsx

There is a bug on multi-round where it only displays the first round. This PR solves the issue.

fix(landing-page): fixed bug with multi round

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

chore: updated pr template

---

packages/interface/src/features/projects/components/VotingWidget.tsx

Changed how the add votes work on the project details page, fixed a small typo on the PR template
fix #582
> [!IMPORTANT]

feat(project-details): improve adding and removing from ballot

---

packages/coordinator/package.json
pnpm-lock.yaml

chore: remove unused packages

---

packages/interface/src/features/ballot/components/AllocationInput.tsx

fix(ballot): fixes a bug where add ballot causing page error

---

packages/interface/src/config.ts
packages/interface/src/features/applications/components/ReviewApplicationDetails.tsx
packages/interface/src/features/projects/components/ProjectContacts.tsx

chore: limit the link length and update links

---

packages/interface/src/components/Footer.tsx
packages/interface/src/layouts/BaseLayout.tsx

Because of the ssr problem, the server rendered outcome would not be the same as the browser, it would cause error.
> [!IMPORTANT]

fix: footer should set ssr to false since it is dynamic to screen size

---

README.md
docs/01_setup.md

Removed coordinator service mentions and added links to the setup guide.
> [!IMPORTANT]
> We do not accept minor grammatical fixes (e.g., correcting typos, rewording sentences) unless they significantly improve clarity in technical documentation. These contributions, while appreciated, are not a priority for merging. If there is a grammatical error, feel free to message the team.

docs: update readme and setup
