privacy-ethereum/maci-platform

- src/components/ConnectButton.tsx
- src/env.js
- src/features/ballot/components/BallotOverview.tsx
- src/features/lists/components/ListEditDistribution.tsx
- src/features/projects/components/AddToBallot.tsx
- src/hooks/useMaciSignup.ts
- src/providers/index.tsx
- src/server/api/routers/ballot.ts
- src/utils/state.ts
I tried the react-error-boundary package to handle all errors in the project, but it's more complex while dealing with async functions, and since they already run mutations and building onError functions for most of the actions, so I gave up and only deal with the errors happening during the signup.
> chore: add error handler for signup

- src/features/ballot/components/BallotOverview.tsx
Remove unused part in `BallotOverview` if the user is not registered yet:
1. number of projects allocated
2. amount of tokens used
> chore: remove unused part of ballot overview if the user is not registered

- src/features/ballot/components/BallotOverview.tsx
- src/layouts/DefaultLayout.tsx
Description:
Currently, if there were projects added to the ballot, but user not on the /ballot page, the main button in BallotOverview would always be No projects added, which is a little bit weird.
The voting due date should be displayed no matter if the user connected their wallet to signup or not.
Also solving issue #69 by not displaying anything if the `appState === "LOADING"`
> feat: modify ballot overview display

- src/layouts/DefaultLayout.tsx
Clear the warning of "duplicate list child with same key".
> fix: remove duplicate child to clear warning

- .env.example
- docs/01_setup.md
- docs/02_adding_projects.md
- docs/03_creating_badgeholders.md
- src/config.ts
- src/contexts/Maci.tsx
- src/env.js
- src/features/distribute/hooks/useAlloPool.ts
- src/hooks/useIsAdmin.ts
- src/layouts/DefaultLayout.tsx
- src/server/api/routers/applications.ts
- src/server/api/routers/projects.ts
- src/server/api/trpc.ts
The problem is we only allow single valid attester in our `EASGatekeeper`, but the frontend config actually accepts multiple users as admins.
We could either do:
1. separate `VALID_ATTESTER` from `NEXT_PUBLIC_ADMIN_ADDRESSES`
2. or just limit the admin to only one
This PR takes the 2nd way, so 
- replace all mention of `NEXT_PUBLIC_ADMIN_ADDRESSES` to `NEXT_PUBLIC_ADMIN_ADDRESS`
- since the `config.admins` were `string[]`, while `config.admin` is just a `string`, rewrite query conditions from `in` or `includes` to `equals` or `===`
- update documentations
**Related Issue**
close #119 and #87
> chore: limit admin to only one person

- src/contexts/Maci.tsx
- src/contexts/types.ts
We call `useSession` and get maci keypair by `data.pubKey` before, but after disposing of storing keypair in session, we should export `maciPubKey` from the `MaciContext`.
> chore: export macipubkey for other components to use

- src/features/applications/components/ApplicationForm.tsx
error:
```
TypeError: Cannot read properties of undefined (reading 'includes')
page: '/applications/new'
```
> fix: add empty array as fallback for impact categories

- public/arrow-down.svg
- public/arrow-up.svg
- src/features/signup/components/FaqItem.tsx
- src/features/signup/components/FaqList.tsx
- src/features/signup/types.ts
- src/layouts/BaseLayout.tsx
- src/layouts/DefaultLayout.tsx
- src/pages/signup/index.tsx
- add FAQ section on the signup page
- this is just an FAQ template, who fork this branch should modify the `FAQList` part.
> feat: add faq components and section on signup page

- e2e/connectWallet.test.ts
fix playwright finding two buttons with same text
> fix: e2e tests

- src/components/Info.tsx
Before we used start time and end time of a certain state to decide whether it's `passed, ongoing, or upcoming`. However, since the poll sometimes deployed before the frontend started, the voting start time and end time is based on the contract, which caused more than one state could be under the `ongoing` state. This would be misleading users, changed to just follow the one and only `appState` by calling `useAppState`.
> fix: wrongly display the round state

- src/components/ui/Form.tsx
- src/components/ui/Tooltip.tsx
- src/features/applications/components/ApplicationForm.tsx
There's no description of what each field is, there's a `hint` param but never used, and it's adding lines under the input field, not sure if it's a good UI for displaying long description, also might need this `Tooltip` widget elsewhere in the whole maci-rpgf project, so made one in the `components/ui`.
Not adding much description about the form fields yet, since I'm not sure how to explain them. Just added two for demo how it looks like.
close #212
> feat: add tooltip

- src/features/projects/components/ProjectItem.tsx
just a small bug, that if there's not any state should be displayed on the buttons section on the `ProjectItem`, a `0` would be displayed, this should be removed.
> fix: 0 being displayed on the projectItem

- src/components/ImageUpload.tsx
- src/components/ui/Tooltip.tsx
- src/features/applications/components/ApplicationButtons.tsx
- src/features/applications/components/ApplicationForm.tsx
- src/features/applications/hooks/useCreateApplication.ts
- src/pages/applications/confirmation.tsx
- this only happens the first time user click on the `next` button after they finished all the required fields, if they close the dialog and click `next` again, could successfully head to next page
- this is because the `useFormContext` not refreshed after some fields finished, only refetch the field values if there are any components re-mounted
#200
> fix: create application form

- packages/interface/src/server/api/routers/projects.ts
Add the filter of roundId back during the `Application` phase.
close #246
> fix: display projects that only in the certain round

- packages/interface/src/contexts/Maci.tsx
catch error instead of letting it display full page error on the website
Since we already has the `Wrong Network` displayed on the wallet button, do nothing on catching this error.
close #245
> fix: remove page error if wrong network

- packages/interface/.env.example
- packages/interface/src/config.ts
- packages/interface/src/contexts/Maci.tsx
- packages/interface/src/env.js
- packages/interface/src/utils/semaphore.ts
Make sure different gatekeepers works well
- FreeForAllGatekeeper
- SemaphoreGatekeeper
Also, use `SemaphoreSubgraph` as default and `SemaphoreEthers` as the fallback option to load semaphore data.
close issue #237
> feat: make sure freeforall and semaphore gatekeeping strategy works

- packages/interface/package.json
- packages/interface/src/contexts/Maci.tsx
- packages/interface/src/utils/hatsProtocol.ts
- pnpm-lock.yaml
Implement signup with HatsProtocol 
close #242
> feat: implement signup with hats

- .github/workflows/checks.yml
- .github/workflows/contracts-build.yml
- packages/contracts/.env.example
- packages/contracts/.gitignore
- packages/contracts/contracts/interfaces/IEAS.sol
- packages/contracts/contracts/interfaces/IRecipientRegistry.sol
- packages/contracts/contracts/mocks/MockEAS.sol
- packages/contracts/contracts/registry/BaseRegistry.sol
- packages/contracts/contracts/registry/EASRegistry.sol
- packages/contracts/hardhat.config.ts
- packages/contracts/package.json
- packages/contracts/tasks/helpers/constants/index.ts
- packages/contracts/tests/EASRegistry.test.ts
- pnpm-lock.yaml
> feat(contracts): add eas registry contract

- .github/workflows/hardhat-tasks.yml
- packages/contracts/contracts/mocks/Mocker.sol
- packages/contracts/deploy-config-example.json
- packages/contracts/hardhat.config.ts
- packages/contracts/package.json
- packages/contracts/scripts/compileSol.ts
- packages/contracts/tasks/deploy/index.ts
- packages/contracts/tasks/deploy/maci/05-pollFactory.ts
- packages/contracts/tasks/deploy/maci/08-maci.ts
- packages/contracts/tasks/helpers/constants/index.ts
- pnpm-lock.yaml
> feat(contracts): add deploy scripts

- .github/workflows/slither.yml
- packages/contracts/.solcover.js
- packages/contracts/contracts/interfaces/ICommon.sol
- packages/contracts/contracts/interfaces/IRecipientRegistry.sol
- packages/contracts/contracts/interfaces/IRegistryManager.sol
- packages/contracts/contracts/mocks/MockRegistry.sol
- packages/contracts/contracts/registry/BaseRegistry.sol
- packages/contracts/contracts/registry/EASRegistry.sol
- packages/contracts/contracts/registryManager/EASRegistryManager.sol
- packages/contracts/contracts/registryManager/RegistryManager.sol
- packages/contracts/tests/EASRegistry.test.ts
- packages/contracts/tests/EASRegistryManager.test.ts
- packages/contracts/tests/RegistryManager.test.ts
- packages/contracts/ts/constants.ts
- packages/contracts/ts/index.ts
> feat(contracts): add registry manager

- .github/workflows/coordinator-build.yml
- packages/coordinator/.env.example
- packages/coordinator/.gitignore
- packages/coordinator/package.json
- packages/coordinator/ts/app.module.ts
- packages/coordinator/ts/common/__tests__/common.test.ts
- packages/coordinator/ts/common/accountAbstraction.ts
- packages/coordinator/ts/common/errors.ts
- packages/coordinator/ts/file/__tests__/file.service.test.ts
- packages/coordinator/ts/file/file.service.ts
- packages/coordinator/ts/proof/proof.service.ts
- packages/coordinator/ts/sessionKeys/__tests__/sessionKeys.controller.test.ts
- packages/coordinator/ts/sessionKeys/__tests__/sessionKeys.service.test.ts
- packages/coordinator/ts/sessionKeys/__tests__/utils.ts
- packages/coordinator/ts/sessionKeys/dto.ts
- packages/coordinator/ts/sessionKeys/sessionKeys.controller.ts
- packages/coordinator/ts/sessionKeys/sessionKeys.module.ts
- packages/coordinator/ts/sessionKeys/sessionKeys.service.ts
- packages/coordinator/ts/sessionKeys/types.ts
- pnpm-lock.yaml
Implement a service to handle session keys generation and management 
re: #266
> feat: session keys service

- packages/contracts/contracts/maci/MACI.sol
- packages/contracts/deploy-config-example.json
- packages/contracts/package.json
- packages/contracts/tasks/deploy/maci/05-pollFactory.ts
- packages/contracts/tasks/deploy/maci/08-maci.ts
- packages/contracts/tasks/deploy/maci/10-registryManager.ts
- packages/contracts/tasks/helpers/constants/index.ts
- packages/contracts/tests/Maci.test.ts
- pnpm-lock.yaml
> chore(contracts): add registry manager deploy task

- packages/interface/src/components/VotingInfo.tsx
- packages/interface/src/features/ballot/components/BallotConfirmation.tsx
- packages/interface/src/features/ballot/components/SubmitBallotButton.tsx
Small copy fixes and prevent negative timeout (re #284 )
> fix: small cleanup and copy fix

- packages/interface/src/features/ballot/components/AllocationInput.tsx
- packages/interface/src/features/projects/components/VotingWidget.tsx
* Disallow decimal numbers in ballot submission
* `decimalScale` is used to [set the allowed number of decimal places](https://s-yadav.github.io/react-number-format/docs/numeric_format#decimalscale-number). A value of zero only allows integers
> fix: disallow decimal numbers in ballot submission

- packages/interface/src/contexts/Ballot.tsx
- packages/interface/src/contexts/Maci.tsx
- packages/interface/src/features/ballot/components/ProjectAvatarWithName.tsx
- Fix an issue where users aren't marked as valid to sign up if using Free For All Gatekeeper.
- Fix an issue where application images are empty or the same if created with an empty or repeated recipient account.
- Fix an issue where QV votes are not calculated correctly during the ballot.
> fix: update gatekeeper, ballot callbacks and fix images for ballots

- packages/interface/src/features/projects/components/ProjectDetails.tsx
- packages/interface/src/pages/projects/[projectId]/Project.tsx
Blurring a non yet accepted application makes it very hard to review it. As it looks like non approved projects do not show up in the main projects page, and also during the application phase they are clearly labelled as not yet approved, maybe this blurring is not needed? @kittybest lmk your thoughts here or if I'm missing something
> chore: do not blur projects which are not approved yet

- .github/workflows/coordinator-build.yml
- packages/coordinator/ts/common/accountAbstraction.ts
- packages/coordinator/ts/common/errors.ts
- packages/coordinator/ts/common/networks.ts
- packages/coordinator/ts/file/file.service.ts
- packages/coordinator/ts/sessionKeys/__tests__/sessionKeys.service.test.ts
- packages/coordinator/ts/sessionKeys/sessionKeys.module.ts
- packages/coordinator/ts/sessionKeys/sessionKeys.service.ts
> fix(coordinator): cleanup session key service and use plaintext approvals

- packages/interface/src/config.ts
> fix(base-sepolia): added base sepolia to the config file

- packages/contracts/contracts/interfaces/IRecipientRegistry.sol
- packages/contracts/contracts/interfaces/IRegistryManager.sol
- packages/contracts/contracts/mocks/MockRegistry.sol
- packages/contracts/contracts/registry/BaseRegistry.sol
- packages/contracts/contracts/registry/EASRegistry.sol
- packages/contracts/tasks/deploy/poll/01-poll.ts
- packages/contracts/tests/EASRegistry.test.ts
- packages/subgraph/schemas/schema.v1.graphql
- packages/subgraph/src/registry.ts
- packages/subgraph/src/utils/entity.ts
- packages/subgraph/templates/subgraph.template.yaml
- packages/subgraph/tests/registry/registry.test.ts
- packages/subgraph/tests/registry/utils.ts
- packages/subgraph/tests/registryManager/registryManager.test.ts
- packages/subgraph/tests/registryManager/utils.ts
Use strings for metadata pointers (note that strings in events to be indexed will be converted to its hash thus bytes32, hence why indexed was removed)
fix shadowing of recipients in EASRegistry
> chore: use strings for metadata on contracts

- packages/contracts/contracts/maci/Poll.sol
- packages/subgraph/config/network.json
- packages/subgraph/src/poll.ts
- packages/subgraph/templates/subgraph.template.yaml
- packages/subgraph/tests/poll/poll.test.ts
- packages/subgraph/tests/poll/utils.ts
Seems call handlers are not supported so replaced it with event handlers
> fix(subgraph): remove call handler and use events for poll init

- packages/contracts/contracts/registry/SimpleRegistry.sol
- packages/contracts/deploy-config-example.json
- packages/contracts/tasks/deploy/poll/01-poll.ts
- packages/contracts/tasks/helpers/constants/index.ts
The arguments for Registry contracts are written in the RegistryManager config field, which looks weird. Move those out, and add `SimpleRegistry` contract base on this PR: #337
> chore: add simple registry and move some arguments to registry config

- packages/coordinator/.env.example
- packages/coordinator/package.json
- packages/coordinator/scripts/uploadRoundMetadata.ts
- packages/subgraph/.gitignore
- packages/subgraph/config/network.example.json
- packages/subgraph/config/network.json
- packages/subgraph/package.json
- packages/subgraph/schemas/schema.v1.graphql
- packages/subgraph/src/poll.ts
- packages/subgraph/templates/subgraph.template.yaml
- pnpm-lock.yaml
- collect round information from the console, upload the information as a json file to the vercel blob storage
- print the url of that json file for user to put inside the `deploy-config.json` file
- add metadataUrl on the subgraph schema for the frontend to fetch
> feat: collect metadata from console and upload

- packages/coordinator/scripts/uploadRoundMetadata.ts
- packages/interface/src/server/api/routers/maci.ts
- packages/interface/src/utils/state.ts
- packages/interface/src/utils/types.ts
If the poll is deployed but not inited, the `initTime` would be `null`, so to display this round data, we would rely on the metadata file. However, once the poll is inited, the `initTime` would be the inited date, then we should change both the `votingStartsAt` and `votingEndsAt` to match the `initTime` and `initTime + duration`.
> feat: update voting start and end time

- packages/contracts/contracts/interfaces/IPayoutStrategy.sol
- packages/contracts/contracts/interfaces/IPoll.sol
- packages/contracts/contracts/maci/Poll.sol
- packages/contracts/contracts/maci/Tally.sol
- packages/contracts/contracts/maci/TallyFactory.sol
- packages/contracts/contracts/mocks/MockERC20.sol
- packages/contracts/deploy-config-example.json
- packages/contracts/package.json
- packages/contracts/tasks/deploy/maci/07-tallyFactory.ts
- packages/contracts/tasks/deploy/poll/01-poll.ts
- packages/contracts/tasks/helpers/constants/index.ts
- packages/contracts/tests/Maci.test.ts
- packages/contracts/tests/Poll.test.ts
- packages/contracts/tests/Tally.test.ts
- packages/contracts/tests/constants.ts
- packages/contracts/tests/utils.ts
- packages/coordinator/package.json
- pnpm-lock.yaml
Next things to do:
1. Subgraph integration
Related to #263
> feat(contracts): payout strategy

- packages/subgraph/src/maci.ts
- packages/subgraph/templates/subgraph.template.yaml
> fix(subgraph): create template for tally to start parsing events

- packages/coordinator/.gitignore
- packages/coordinator/round-metadata-example.json
- packages/coordinator/scripts/uploadRoundMetadata.ts
> feat: improve the upload metadata process

- packages/contracts/tasks/runner/initPoll.ts
- packages/contracts/tasks/runner/submitOnChain.ts
Minor refactoring for submit onchain task
> refactor: submit onchain improvements

- packages/interface/src/server/api/routers/maci.ts
- packages/interface/src/utils/fetchTally.ts
- packages/interface/src/utils/types.ts
How to use:
```js
import { api } from "~/utils/api";
...
const tally = api.maci.tally.useQuery({ id: "TallyContractAddress" });
// Use the results from the tally.
```
> feat(tally-fetch): Added fetch from subgraph

- .github/workflows/e2e.yml
Disable cache for synpress run to avoid issues with old version tests
> chore: remove caching for synpress runs

- packages/interface/src/components/ImageUpload.tsx
- packages/interface/src/components/ui/Form.tsx
- packages/interface/src/features/applications/components/ApplicationsToApprove.tsx
**Problem**
The `Form` component uses pages for forms that have multiple sections. In each section the inputs already alert the user about some conditions (e.g.: you need a valid eth address, this field needs at least 3 words, etc). 
The problem happens in the end. If the user ignored the warnings of each input in each section, then the form is not valid and cannot be submitted. When the user press the submit button nothing happens (no alert).
**Solution**
Detect if the form has any validation errors and tell the user that when he presses the submit button. That way the user will know he needs to trace back and find the input validation error.
**Extras**
1. Delete "Applications" from top navbar
2. "Create New Application" button in each round sends to the `/rounds/[roundId]/new` page
> fix(form): show error at the end if inputs are not valid

- packages/interface/src/utils/fetchTally.ts
> fix: catch error for fetch subgraph

- packages/interface/src/components/ConnectButton.tsx
- packages/interface/src/components/Header.tsx
- packages/interface/src/components/Info.tsx
- packages/interface/src/components/SingleRoundHome.tsx
- packages/interface/src/hooks/useIsMobile.ts
- packages/interface/src/pages/index.tsx
- packages/interface/src/utils/types.ts
- packages/subgraph/package.json
Since there's need for only running single round, add the single round UI back but slightly modify the displayed information and alignment.
> feat: update single round UI and slightly update the mobile UI

- packages/interface/src/features/ballot/components/BallotConfirmation.tsx
- packages/interface/src/layouts/types.ts
- packages/interface/src/pages/index.tsx
- packages/interface/src/pages/rounds/[pollId]/applications/confirmation.tsx
- packages/interface/src/pages/rounds/[pollId]/applications/index.tsx
- packages/interface/src/pages/rounds/[pollId]/applications/new.tsx
- packages/interface/src/pages/rounds/[pollId]/ballot/confirmation.tsx
> fix: nav bar display and the singleRound stuff

- packages/interface/src/layouts/BaseLayout.tsx
- packages/interface/src/layouts/types.ts
- packages/interface/src/pages/rounds/[pollId]/ballot/index.tsx
We add `requireRegistration` on the ballot page item, when refreshing, it takes time for the frontend to check if the user is registered or not. There should be another method deal with this condition instead of pushing them directly to the homepage.
close #540
> fix: ballot page refresh redirect to homepage

- packages/interface/src/components/BallotOverview.tsx
- packages/interface/src/components/Info.tsx
- packages/interface/src/contexts/Maci.tsx
- packages/interface/src/contexts/types.ts
- packages/interface/src/features/ballot/components/SubmitBallotButton.tsx
- packages/interface/src/layouts/DefaultLayout.tsx
> chore: improve the ballot submission process

- packages/interface/src/features/ballot/components/ProjectAvatarWithName.tsx
- packages/interface/src/features/rounds/components/RoundItem.tsx
- packages/interface/src/features/rounds/components/RoundsList.tsx
- packages/interface/src/pages/index.tsx
> fix: adjust ui styling

- packages/interface/src/contexts/Maci.tsx
- packages/interface/src/features/rounds/components/RoundItem.tsx
Fixed #539 and an interface bug on multi round
> fix(ballot-rejected): fixed error message and scrollbar in overflow

- packages/interface/src/features/ballot/components/BallotConfirmation.tsx
> feat: add share sns cta

- packages/interface/package.json
- packages/interface/scripts/genGitHash.js
- packages/interface/src/components/Footer.tsx
- packages/interface/src/config.ts
- packages/interface/src/env.js
- packages/interface/src/pages/coordinator/index.tsx
close #551 
**Discussion**
1. Is there any easier way to accomplish this? 
2. should the commit be displayed to everyone during the `development` mode? or only the organizer?
3. where to put it?
> feat: display git commit version 

- packages/interface/src/components/BallotOverview.tsx
- packages/interface/src/components/Footer.tsx
- packages/interface/src/components/Header.tsx
- packages/interface/src/features/ballot/components/BallotConfirmation.tsx
- packages/interface/src/features/home/components/FaqItem.tsx
- packages/interface/src/features/projects/components/ProjectItem.tsx
collet all the small ui issues here. So make it a draft PR until no more issues are found in 3 work days.
**Relate Issues**
close #560  #561
> chore: adjust ui bugs

- packages/interface/src/features/applications/components/ApplicationForm.tsx
- packages/interface/src/features/applications/components/ReviewApplicationDetails.tsx
- packages/interface/src/features/projects/components/ProjectDescriptionSection.tsx
- packages/interface/src/features/projects/components/ProjectDetails.tsx
- packages/interface/src/features/projects/components/ProjectItem.tsx
- packages/interface/src/styles/globals.css
- packages/interface/src/utils/removeMarkdown.ts
- pnpm-lock.yaml
Added support for markdown on the description fields and the Details. Fix #326
> [!IMPORTANT]
> feat(markdown-support): added markdown support

- packages/interface/src/features/applications/components/ApplicationItem.tsx
- packages/interface/src/features/applications/components/ReviewApplicationDetails.tsx
- packages/interface/src/features/projects/components/ProjectItem.tsx
- packages/interface/src/utils/types.ts
Added preview card during application review and updated the applications table to show a short summary.
fix #586
> [!IMPORTANT]
> feat(application-review): added card and updated review page

- packages/interface/src/server/api/routers/results.ts
- packages/subgraph/README.md
- packages/subgraph/package.json
- packages/subgraph/src/utils/entity.ts
- packages/subgraph/tests/tally/tally.test.ts
This is to solve the tallyResult id collision on the subgraph, meanwhile make sure the interface works well after this change.
Because of the rebase issue, this is same PR as #584  & #583 , but branch from the latest `main` branch.
I found that the interface mapping result with tally result never uses the result id, that's why we didn't find this problem before. We need to have 100% confidence that the subgraph returns tally result 1 by 1 following the index of the projects.
(So actually, maybe it's better that we use the `result.id` instead of the `index` of the loop?)
see here:
https://github.com/privacy-scaling-explorations/maci-platform/blob/c0e35afe42083c6580f64b2ae4c2ce6658458a29/packages/interface/src/server/api/routers/results.ts#L61-L68
> [!IMPORTANT]
> We do not accept minor …
> fix: tally result id collision

- packages/interface/src/features/applications/components/ApplicationForm.tsx
- packages/interface/src/features/applications/components/ReviewApplicationDetails.tsx
- packages/interface/src/features/applications/hooks/useApplicationById.ts
- packages/interface/src/features/applications/hooks/useApplications.ts
- packages/interface/src/features/applications/hooks/useCreateApplication.ts
- packages/interface/src/features/applications/types/index.ts
- packages/interface/src/features/projects/components/ProjectItem.tsx
- packages/interface/src/features/projects/components/ProjectsResults.tsx
- packages/interface/src/features/rounds/components/Projects.tsx
- packages/interface/src/hooks/useRegistry.ts
- packages/interface/src/pages/rounds/[pollId]/applications/confirmation.tsx
- packages/interface/src/server/api/routers/applications.ts
- packages/interface/src/server/api/routers/projects.ts
- packages/interface/src/utils/fetchApplications.ts
- packages/interface/src/utils/fetchProjects.ts
This PR is trying to figure out what is the best way to display the projects to the user during the application registration period, since they might wanna check if their application is approved or not, and they might want to edit it.
Method 1: (Which is now implemented in this PR)
store user's projectId in the localStorage, load those projects separately and display on the top area of the project dashboard.
- Why store the ids in the localStorage? because the one upload this project might not be the one holding that payout address
- Why display in a separate area instead of display them altogether but just add a highlight border or tag on it? we could discuss more about it, **display in a separate block** or **display altogether with other approved projects**
- Why the …
> feat: display the projects created by the user

- packages/interface/src/components/Header.tsx
This PR fixes #511
> [!IMPORTANT]
> fix: dark/light mode mode not set to default

- packages/interface/src/features/applications/components/ApplicationItem.tsx
The project listing image becomes stretched when the project description contains too much text. This PR ensures that the image block maintains its proper spacing.
> [!IMPORTANT]
> fix: resolve project listing issue

- packages/interface/src/components/Header.tsx
- packages/interface/src/components/HelpButton.tsx
- packages/interface/src/features/applications/components/ApplicationItem.tsx
- packages/interface/src/features/home/components/FaqList.tsx
- packages/interface/src/features/home/components/Glossary.tsx
- packages/interface/src/features/projects/components/VotingWidget.tsx
- packages/interface/src/pages/_app.tsx
- packages/interface/src/pages/index.tsx
- packages/interface/src/pages/rounds/[pollId]/ballot/index.tsx
- packages/interface/src/styles/HelpButton.css
- pnpm-lock.yaml
added glossary, help button, renamed ballot
> [!IMPORTANT]
> feat(glossary): added glossary, help button, renamed ballot

- packages/interface/src/features/rounds/components/Projects.tsx
- packages/interface/src/hooks/useRandomizedProjects.ts
This PR fixes #553 
Randomize the display of projects by generating a random seed stored in local storage. 
The seed ensures that the project list appears in the same randomized order every time the user returns to the dashboard.
> [!IMPORTANT]
> feat: randomize display of projects by adding a random seed in locale storage

- packages/contracts/contracts/interfaces/IPayoutStrategy.sol
- packages/contracts/contracts/maci/Tally.sol
- packages/contracts/tests/Tally.test.ts
Remove unnecessary `withdrawExtra`. This reduces trust required in the `owner` as they cannot withdraw arbitrarily large amounts of funds 
> [!IMPORTANT]
> feat: remove withdrawExtra

- packages/contracts/contracts/interfaces/IPayoutStrategy.sol
- packages/contracts/contracts/maci/Tally.sol
- packages/contracts/deploy-config-example.json
- packages/contracts/tasks/deploy/poll/01-poll.ts
- packages/contracts/tests/Tally.test.ts
- packages/subgraph/schemas/schema.v1.graphql
- packages/subgraph/src/maci.ts
- packages/subgraph/src/utils/entity.ts
- packages/subgraph/tests/common.ts
- packages/subgraph/tests/maci/maci.test.ts
This pull request refactors the Tally contract's post-poll fund management by replacing the previous cooldown mechanism with a more explicit deposit window. This makes the period for depositing funds after a poll ends clearer and more configurable. The change is reflected across the Solidity contracts, deployment scripts, tests, and subgraph schema/indexing logic.
Key changes include:
**Smart Contract Logic Updates:**
- Removed the `cooldownTime` parameter and related logic. Added `depositWindow` parameter, which defines how long after a poll ends deposits are accepted. The contract now enforces deposit and claim actions based on this window, using new modifiers and error types. (`IPayoutStrategy.sol`, `Tally.sol`) [[1]](diffhunk://#diff-6918d43eeb98ac1c2e3daaa3f837b55b8788438fda9731b9ff6d …
> feat: add deposit window to tally contract

- packages/contracts/contracts/interfaces/IPayoutStrategy.sol
- packages/contracts/contracts/maci/Tally.sol
- packages/contracts/deploy-config-example.json
- packages/contracts/tasks/deploy/poll/01-poll.ts
- packages/contracts/tests/Tally.test.ts
- packages/subgraph/schemas/schema.v1.graphql
- packages/subgraph/src/maci.ts
- packages/subgraph/src/utils/entity.ts
- packages/subgraph/tests/common.ts
- packages/subgraph/tests/maci/maci.test.ts
**Re-add withdrawal function with changes**
* Add withdraw function that can be called after a cooldown
* Funds can only be sent to a preconfigured custodian (Can set this to a gitcoin wallet for production deploy) - this balances having an escape hatch, while also reducing trust assumptions of the owner.
* Can call withdraw only after tallying is complete
**Minor simplifications**
* Removes `depositWindow` not essential as deposits can stop after tallying is complete 
* Removes pause functionality - no longer needed as this contract will be audited
**Other changes**
* Remove `duringDepositWindow` & `afterDepositWindow` modifiers
* `claim` can be called directly after tallying finishes
> [!IMPORTANT]
> We do not accept minor grammatical fixes (e.g., correcting typos, rewording sentences) …
> feat: add withdraw function
